#pragma once

#define CONFIG_SPEED 13000.f
#define CONFIG_JUMP_FORCE 200.f
#define CONFIG_GRAVITY -300.f
#define CONFIG_ENERGY_RELOAD_RATE 25.f

#define CONFIG_Y_TERMINAL_VELOCITY -100.f

#define CONFIG_GRID_UNIT 400.f
#define CONFIG_GRID_UNIT_UP 50.f

#define CONFIG_GAME_NAME "Quantum Ranger"